### PR TITLE
Make HTTP timeout configurable; default to 30 seconds

### PR DESCRIPTION
**Pull request by henryaj**

### CODE REVIEW

**Review by peterebden — APPROVED** [review]
Thanks, looks good!

**Comment by henryaj** [comment]
:+1: Might also be worth updating the readme with a note about the new default.

**Comment by henryaj** [comment]
can u merge pls @peterebden :)

**Comment by peterebden** [comment]
Oh sorry, thought you could. Will do, you can ask Mike about becoming part of the thought-machine org if you want 🙂

**Comment by macripps** [comment]
Invite has been sent

**Pull request merged**
